name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test_var
      id: test_var
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_var
        setup-command: 'sed -i -e ''s/username=/username="admin" #/'' -e ''s/password_length=/password_length=12
          #/'' main.py'
        command: python main.py
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_VAR_RESULTS: "${{steps.test_var.outputs.result}}"
      with:
        runners: test_var
